image: python:3.7.5

before_script:
  - python -V

stages: 
  - test

test_job: 
  stage: test
  script:
    - echo "Checking PEP8"
    - pip install -r requirements.txt
    - pycodestyle $(find . -name "*.py")
    - echo "Running tests"
    - python -m unittest discover tests/unit "*.py"