image: python:3.7.5

before_script:
  - python -V

stages: 
  - test

test_job: 
  stage: test
  script:
    - echo "Checking PEP8"
    - pip install -r requirements.txt
    - pycodestyle $(find norminette/ -d -name "*.py")
    - echo "Running Lexer Unit Tests"
    - cd norminette && python -m unittest discover tests/unit "*.py"
    - echo "Running Lexer tests on files"
    - cd norminette && python -m unittest discover tests/files "*.py"
